### ISSUE TITLE
キャラクターのいない音声合成ライブラリ（VOICEVOX Nemo）を作る

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_project#30]
VOICEVOX Nemoを作成するためのメモ用のIssueです。
とりあえず最初のバージョンが提供され始めればclose。

## 設計

エディタとしては提供せず、vvppをダウンロードしてVOICEVOX本体に導入する構成。
コアのデプロイ先は[VOICEVOX/voicevox_nemo_core](https://github.com/VOICEVOX/voicevox_nemo_core)、ビルドは秘匿リポジトリで。
エンジンのデプロイ先は[VOICEVOX/voicevox_nemo_engine](https://github.com/VOICEVOX/voicevox_nemo_engine)、ビルドも同一リポジトリで。

## タスク表

- [x] リソースを用意する
	- [x] アーキテクチャを考える
- [x] コアをビルドする
	- [x] アーキテクチャを考える
- [x] エンジンをビルドする
	- [x] アーキテクチャを考える
- [ ] ホームページを作る

## リソースのアーキテクチャ

VOICEVOX Nemo用のリポジトリ（[voicevox_nemo_resource](https://github.com/VOICEVOX/voicevox_nemo_resource)）を作る

- リポジトリ上でNemo用のディレクトリを作る
	- forkしてリソースを置き換える形にするとコンフリクトが毎回発生してしまうため

### 概要
製品版はprivateリポジトリでビルドし、公開リポジトリにデプロイする。
リポジトリ名だけ`voicevox_nemo_core`にしてファイル名などは`voicevox_core`のままにする。
公開リポジトリ上で製品ビルドが可能になったら名称を全て`voicevox_nemo_core`とする。
名称が`voicevox_core`のときはプレビュー版とし、READMEでもそう案内する。

### 詳細
- 製品版は通常のVOICEVOXと同様にprivateリポジトリ側でビルドする
- 名称は`voicevox_nemo_core`が望ましい
	- リポジトリ名、dll、zip名、python wheelなど
	- 案内する名称も変更すべき
		- READMEでの案内、downloaderがダウンロードする先
- リポジトリ名だけは`voicevox_nemo_core`にし、それ以外は`voicevox_core`としたい
	- 一旦作ってデプロイしてみるところまではなるべく簡単にしておきたい
	- 名称変更は影響範囲が広くて追従するたびにおそらくテストが落ちまくる
	- ので、気軽にテストできるよう公開リポジトリでのビルドが可能になるまでは名前変更を避けたい
	- また、将来的にVVMが完成すれば通常のVOICEVOXコアと全く同じになるかもしれないのでちょっと後回しにしておきたい

## エンジンのビルドのアーキテクチャ
コアと同様。
manifestファイルだけはVOICEVOXエンジンと違うものにする。

- 将来的にVVMが完成したらNemo専用エンジンの提供はなくなる可能性がある
	- 音声ライブラリインストールという形に変わる

## ホームページを作る

内容リスト

- [x] トップの情報
- [x] トップの画像
- [x] 特徴リスト
- [x] サブのキャッチコピー
- [x] 各話者の情報
	- [x] サンプルボイス
	- [x] CV？
	- [x] リンク？
- [x] ダウンロード・インストール方法案内
	- [x] 流れ説明
	- [x] VOICEVOXインストール案内
	- [x] Nemoインストール案内
	- [x] （Nemo音声とVOICEVOXキャラ音声の利用規約は違うことを案内）
- [x] 右上のダウンロードボタンの挙動変更
- [x] インストール方法案内をNemo仕様に
- [ ] エンジンの紹介
- [ ] コアの紹介
- [x] サムネイル作成
- [x] （VOICEVOX Nemoとは）
- [x] （ダウンロード数把握）
- [x] VOICEVOXの利用規約はVOICEVOXのものだとわかるようなタイトルにする
- [x] バージョンアップ
- [ ] （トップページのVOICEVOX Nemoのとこにサムネ表示）

## エディタ

- [x] vvppダブルクリック時にダイアログ内でマルチエンジンをONにするissue作成
- [x] マルチエンジン機能を実験的機能から通常機能にあげる
- [x] マルチエンジン機能周りの使い方を更新

## エンジン

- [x] Nemoエンジンの使い方追記
	- [x] dockerhub
	- [x] github readme
	- [x] github リリースノート

## その他

- [x] NemoコアのREADMEでプレビュー版であるということを案内

**Comment by Hiroshiba** [comment]
コアのビルドが完了したのでメモです。

- バージョンは、マイナーバージョンまでコアと一緒で、パッチバージョンはコアと独立する
	- なので今回は[0.14.0](https://github.com/VOICEVOX/voicevox_nemo_core/releases/tag/0.14.0)
- リポジトリは`voicevox_nemo_core`、dllの名称などは`voicevox_core`
	- （事情はissueの内容へ）

**Comment by Hiroshiba** [comment]
リソースのリリースができたのでメモです。

- https://github.com/VOICEVOX/voicevox_nemo_resource/releases/tag/0.14.0

**Comment by Hiroshiba** [comment]
エンジンのビルドがとりあえず完成したのでメモです。
https://github.com/VOICEVOX/voicevox_nemo_engine/releases/tag/0.14.0

* ポートは50121にした
* 辞書のファイルパスを変えた

**Comment by Hiroshiba** [comment]
webページ作成中です。
デザインができる方の提案でホームページの背景色をグラデーションにしようとしてcssを頑張っていたのですが、レスポンシブ×グラデーションはめちゃめちゃ大変だということを体感しました。
一応供養のためにcssメモです。。

<details>

```css

.nemo {
  color: white;

  &::before {
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: -1;
    background: radial-gradient(
        circle at 0 0,
        rgba(87, 188, 162, 1),
        rgba(87, 188, 162, 0.05) 50%,
        rgba(0, 0, 0, 0) 100%
      ),
      radial-gradient(
        circle at 100% 0,
        rgba(47, 93, 235, 1),
        rgba(0, 0, 0, 0) 80%
      ),
      radial-gradient(
        circle at 0 100%,
        rgba(31, 35, 51, 1),
        rgba(0, 0, 0, 0) 100%
      ),
      linear-gradient(0deg, rgba(31, 35, 51, 1), rgba(0, 0, 0, 0) 100%),
      rgba(0, 0, 39, 1);
    background-blend-mode: normal, normal, normal, normal, multiply;
    filter: brightness(0.85);
  }
}
```

</details>
