### ISSUE TITLE
テストが通ったら自動的にマージできるようにしたい

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_project#53]
## 内容

テストが通ったら自動的にマージできるようにしたいです。

`merge queue`を使えば可能なはずなのですが、VOICEVOXのレビュー＆approve事情に合ってないためそのままでは適用できなさそうでした。

VOICEVOXのプルリクエストマージは、以下の2つの条件のうちどちらかを満たすと可能としています。

* `@maintainer`チームの１人のapprove
* `@reviewer`チームの２人のapprove

branch protectionを使えば「何人以上のapproveが必要か」と「誰ならforce mergeが可能か」を設定できます。
なので、2人以上のapproveがあるか、`@maintainer`チームのforce mergeを有効にすることで、↑のどちらの条件でもマージできるようにしています。

問題はこれが`merge queue`で使えないっぽいことです。
というのも、「N人以上のapprove」では`merge queue`を使えますが、force mergeの場合は`merge queue`を無視して対象のブランチにマージするという挙動をするっぽいです。

さてどうしようかなという感じです･･･ 😇 

### 実現方法

いくつか解決策はあると思います。とりあえず列挙してみます。

* `@maintainer`のapproveがあれば自動でapproveしてくれるbotを追加する
	* botに承認してもらうことで「２人がapproveしている」という条件を満たす
	* これが一番手っ取り早い気がしています
	* https://github.com/hiho-check-organization/check-auto-merge で試していたのですが、権限周りでつまづいたので一旦諦めました
	* たぶんorgの情報を見れるPATを設定しないといけない･･･？
* `Branch protection rule`による判定ではなく、専用のマージ可否判定Github Actionsを作る
	* これが一番柔軟そうではある
	* けどなんか結構大変そう
	* `merge queue`に登録するAPIが無さそう･･･？だから不可能かも･･･？
	* 専用のActionsでマージ可否判定→botがapprove→botのapproveがあれば`merge queue`可能になる`Branch protection rule`　なら可能かも
* マージ条件の方を変える
	* いい条件が思いつかない･･･。

## その他

メモです。

* `merge-queue`はorganizationを作ってその下じゃないとテストできない
	* organization作るのは無料でできるのでサクッと作っちゃえば良いはず
* `Branch protection rule`だけじゃなく`Rulesets`でも`merge queue`を作れる
	* `ruleset`はexportもできるのでこっちの方が便利そう

**Comment by Hiroshiba** [comment]
もし挑戦してみたい方がいらっしゃったらコメントください 🙇 
条件等も細かいところが分かりづらいと思うので何でもお聞きください！

**Comment by Hiroshiba** [comment]
@VOICEVOX/maintainer すみません、ちょっと勝手にプロジェクト作ってしまいました 🙇 

オートマージしたく色々試してみたのですが、github の仕様とVOICEVOXの要件が合いませんでした･･･。
このプロジェクトリポジトリに作るissueとしてはちょっと規模感が小さいかもなので、移動した方が良さそうだったら移動します 🙇

**Comment by Hiroshiba** [comment]
この頃から色々状況が変わっている気がする＆あと Discord で色々議論したのでメモを追加します！
Discordの議論は[この辺り](https://discordapp.com/channels/879570910208733277/893889888208977960/1322872743493894215)。

この時と違い、merge queueはBranch Protectionが必須じゃなくなりました。
おそらく今は「いつでもmerge queueは使え、マージカードも同じ条件になったらmerge queueが発動してマージできる」だと思います。

ということで、例えば`ruleset`の`Require status checks to pass`を利用し、以下の方針とかが考えられそうです。

1. 必要なApprove数をチェックするGithub Workflowを作る  
2. そのワークフローの結果をrulesetの必須チェックに設定  
3. 十分な手動Approveがあればワークフローを成功にし、他のテストと合わせて条件を満たしたら`merge queue`が発動するようにする

これならBotによる自動Approveを行わなくても運用できそう。

**Comment by sevenc-nanashi** [comment]
試作しました：
https://github.com/nanatsuki-testing/merge-queue

こんな仕様になっています：
- メンテナロール持ちが自動マージを有効化（≒マージキューに入れる）するとマージを許可
- レビュワーロール持ちが自動マージを有効化した時、レビュワーロール持ちによるApproveレビューが2個あれば許可
- それ以外は却下

要件をちゃんと満たしてそう？

**Comment by Hiroshiba** [comment]
リポジトリ眺めさせていただきました、良さそう！！
（ChatGPTに解説を頼んでみた感じ、結構わかりやすかった。）
https://chatgpt.com/share/677282f3-dbd0-8008-9d52-986060e1e105

ぜひVOICEVOX内で運用してみたい気持ちでいます！
コードをどう管理するか相談したみ。ちょっとたたき台として案出してみます！

コード読むに汎用的なGithub Actionsにすることも可能そうではあるけど、VOICEVOX Org内で専用に管理したほうが楽そうな気がしました！
メンテナ・レビュワーチームがいたり、人数がマジックナンバーになってる設計になってたり。
なのでVOICEVOX Org下にGithub Actionsを置いて、それを使う専用のworkflowをmerge queue使いたい側のリポジトリに置くのが無難･･･でしょうか。

merge queueはいろんなとこで使いたくて、ファイル配置していくのちょっと大変かもではありますね。
merge queue管理リポジトリを作って、そこに登録したリポジトリは自動で見てくれる設計ができれば楽そうだけど、他のリポジトリのPRやmerge queue OKをトリガーに動かせないと難しそう。

あ、各リポジトリからGithub Acitionsを呼び出す形で行く場合、もし可能ならメンテナチーム名やレビュワーチーム名は指定にできそうでしょうか 🙇 
確か今VOICEVOXのレビュワーチームは全リポジトリ共通なのですが、メンテナチームはリポジトリごとに異なるので･･･！
（まあ共通でも問題なさそうだけど）

**Comment by sevenc-nanashi** [comment]
> なのでVOICEVOX Org下にGithub Actionsを置いて、それを使う専用のworkflowをmerge queue使いたい側のリポジトリに置くのが無難･･･でしょうか。

ですね。具体的には色々なリポにこんなWorkflowを置く形になると思います：

<details>
<summary>そんなWorkflow</summary>
```yml
on:
  pull_request_target:
    types: [auto_merge_enabled]
  merge_group:
    types: [checks_requested]

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - uses: voicevox/review-checker@main
        with:
          token: ${{ secrets.OWNER_TOKEN }}
          event: ${{ toJson(github.event) }}
          ref: ${{ github.ref }}
```

</details>


> あ、各リポジトリからGithub Actionsを呼び出す形で行く場合、もし可能ならメンテナチーム名やレビュワーチーム名は指定にできそうでしょうか 🙇
確か今VOICEVOXのレビュワーチームは全リポジトリ共通なのですが、メンテナチームはリポジトリごとに異なるので･･･！

入力でメンテナチーム名を受け取る感じにすればいい感じになるかも？

> コード読むに汎用的なGithub Actionsにすることも可能そうではあるけど、VOICEVOX Org内で専用に管理したほうが楽そうな気がしました！
> メンテナ・レビュワーチームがいたり、人数がマジックナンバーになってる設計になってたり。

こう、こんな感じにすれば他のリポでも使えるかなぁとか思ったりしました：
```yml
      - uses: voicevox/review-checker@v1
        with:
          token: ${{ secrets.OWNER_TOKEN }}
          event: ${{ toJson(github.event) }}
          ref: ${{ github.ref }}

          required_score: 2
          score_rules: |
            maintainer: 2
            reviewer: 1
```

**Comment by sevenc-nanashi** [comment]
actionに切り出してみました：
https://github.com/sevenc-nanashi/approve-counter

チームやロールの指定が良い感じにできるようになっています。

**Comment by Hiroshiba** [comment]
良さそう！！！　コードも一旦なんとなく眺めさせていただきました！
（readmeとファイルはMITライセンスだけどpackage.jsonに書かれてるのはISCになってるかも）

```yaml
on:
  pull_request_target:
    types: [auto_merge_enabled]
  merge_group:
    types: [checks_requested]
```
と２つ書かないといけないのが疑問でした（`pull_request_target`だけでも良さそう）が、下の方も仕様上必要な感じですよね。
であれば今の仕様が良さそう！

---

Discordで少し話した件ですが、preview-pages同様にVOICEVOX Org内で管理するのはどうでしょうか？
VOICEVOXが使いやすい形を保つのが嬉しそうなのと、あとOrg内のGithub Actionsをメンテする経験を積んでみたいためです（後者は完全に私的な理由ですが）。

ただ１点、もしVOICEVOXにとっては不要な提案や変更が来たときのスタンスが変わってきそうです。
@sevenc-nanashi さんリポジトリであればここの方針は自由だけど、VOICEVOX的には優先度が相当低いのでモチベーション的に微妙かも。
ここのどれくらい汎用的にしたいかがポイントかもです。（あとレビューが入る点）
これもどちらでも良い感じであれば、ぜひVOICEVOX Orgリポジトリで進行できると嬉しいです！！

リポジトリ作っていただいて、preveiew-pagesのときみたくinitialコミットとして全部PRいただければ！！ 🙏 
今の段階のコメントとしてはこんな感じです：

* 採用技術に異論なしです
  * biomeがVOICEVOX的には新技術で、採用する場合は知見を @sevenc-nanashi さんに頼りたい気持ち！
* distを書き出すまでの手法はREADMEに書かれてると嬉しいかも
  * 他の人がメンテしやすい＆数年後の我々を助けてくれる
* `src/index.ts`の処理の大まかな単位ごとに、何やってるかの一言コメントが書かれてるとたぶんメンテしやすそう
* auto mergeボタンが押されてからマージされるまでのシーケンス図があると嬉しそう
  * だけどこれは結構作るの大変そうだし、なくても良さそう？
* リポジトリ名悩む
  * ボイボ的には、「approveをカウントする」以外にマージをブロックしたい可能性があるか次第かも
  * なさそうな気もする
  * 機能名の方で名付けるなら`merge-gatekeeper`とかもありかも [ChatGPTの案](https://chatgpt.com/share/677373e5-ffcc-8008-b9ae-4a5d0dfbf9e1)
